const response = {
    "pagination": {
    "limit": 25,
    "offset": 0,
    "count": 25,
    "total": 10000
    },
    "data": [
    {
    "author": null,
    "title": "Omega Therapeutics Reports Fourth Quarter and Full Year 2022 Financial Results and Provides Corporate Update",
    "description": "(marketscreener.com) Advanced Company&rsquo;s Lead Program, OTX-2002, in the Clinic; Preliminary Data from Phase 1/2 MYCHELANGELO&trade; I Trial Anticipated in 2023 Progressed IND-enabling Studies for OTX-2101; Company&rsquo;s Development Candidate for MYC-driven Non-Small Cell Lung Cancer to Utilize a Novel Lung-Targeting Lipid Nanoparticle Ended the Year with Cash,...https://www.marketscreener.com/quote/stock/OMEGA-THERAPEUTICS-INC-125290480/news/Omega-Therapeutics-Reports-Fourth-Quarter-and-Full-Year-2022-Financial-Results-and-Provides-Corporat-43121209/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/OMEGA-THERAPEUTICS-INC-125290480/news/Omega-Therapeutics-Reports-Fourth-Quarter-and-Full-Year-2022-Financial-Results-and-Provides-Corporat-43121209/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:02+00:00"
    },
    {
    "author": null,
    "title": "Paramount Gold Nevada Announces Term Sheet for Financing of up to $15 Million With Sprott",
    "description": "(marketscreener.com) WINNEMUCCA, Nev., March 01, 2023 -- Paramount Gold Nevada Corp. announced today that it has executed a non-binding term sheet with Sprott Resource and Streaming Royalty Corp. , for a Royalty Convertible Note providing for minimum proceeds of $10 million and maximum proceeds of up to $15 million. While substantial technical and legal due...https://www.marketscreener.com/quote/stock/PARAMOUNT-GOLD-NEVADA-COR-22148865/news/Paramount-Gold-Nevada-Announces-Term-Sheet-for-Financing-of-up-to-15-Million-With-Sprott-43121208/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/PARAMOUNT-GOLD-NEVADA-COR-22148865/news/Paramount-Gold-Nevada-Announces-Term-Sheet-for-Financing-of-up-to-15-Million-With-Sprott-43121208/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:02+00:00"
    },
    {
    "author": null,
    "title": "TScan Therapeutics to Participate in the Cowen 43rd Annual Health Care Conference",
    "description": "(marketscreener.com) WALTHAM, Mass., March 01, 2023 -- TScan Therapeutics, Inc. , a clinical-stage biopharmaceutical company focused on the development of T cell receptor -engineered T cell therapies for the treatment of patients with cancer, today announced that the Company will participate in a panel discussion at the Cowen 43rd Annual Health Care...https://www.marketscreener.com/quote/stock/TSCAN-THERAPEUTICS-INC-124803355/news/TScan-Therapeutics-to-Participate-in-the-Cowen-43rd-Annual-Health-Care-Conference-43121204/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/TSCAN-THERAPEUTICS-INC-124803355/news/TScan-Therapeutics-to-Participate-in-the-Cowen-43rd-Annual-Health-Care-Conference-43121204/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:02+00:00"
    },
    {
    "author": null,
    "title": "Apellis Pharmaceuticals to Present at Upcoming Investor Conferences",
    "description": "(marketscreener.com) WALTHAM, Mass., March 01, 2023 -- Apellis Pharmaceuticals,&nbsp;Inc., , a global biopharmaceutical company and leader in complement, today announced that the company will participate in the following March investor conferences: Cowen 43rd Annual Healthcare Conference: Fireside chat on Wednesday, March 8, 2023, at 9:10 a.m....https://www.marketscreener.com/quote/stock/APELLIS-PHARMACEUTICALS-38607086/news/Apellis-Pharmaceuticals-to-Present-at-Upcoming-Investor-Conferences-43121203/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/APELLIS-PHARMACEUTICALS-38607086/news/Apellis-Pharmaceuticals-to-Present-at-Upcoming-Investor-Conferences-43121203/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:02+00:00"
    },
    {
    "author": null,
    "title": "TScan Therapeutics to Participate in the Cowen 43rd Annual Health Care Conference",
    "description": "(marketscreener.com) WALTHAM, Mass., March 01, 2023 -- TScan Therapeutics, Inc. , a clinical-stage biopharmaceutical company focused on the development of T cell receptor -engineered T cell therapies for the treatment of patients with cancer, today announced that the Company will participate in a panel discussion at the Cowen 43rd Annual Health Care Conference...https://www.marketscreener.com/quote/stock/TSCAN-THERAPEUTICS-INC-124803355/news/TScan-Therapeutics-to-Participate-in-the-Cowen-43rd-Annual-Health-Care-Conference-43121200/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/TSCAN-THERAPEUTICS-INC-124803355/news/TScan-Therapeutics-to-Participate-in-the-Cowen-43rd-Annual-Health-Care-Conference-43121200/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:02+00:00"
    },
    {
    "author": null,
    "title": "Kymera Therapeutics to Participate in Upcoming March Investor Conferences",
    "description": "(marketscreener.com) WATERTOWN, Mass., March 01, 2023 -- Kymera Therapeutics, Inc. , a clinical-stage biopharmaceutical company advancing targeted protein degradation to deliver novel small molecule protein degrader medicines, today announced that the Company&rsquo;s management team will attend the following upcoming investor events: Cowen 43rd Annual Health...https://www.marketscreener.com/quote/stock/KYMERA-THERAPEUTICS-INC-111169997/news/Kymera-Therapeutics-to-Participate-in-Upcoming-March-Investor-Conferences-43121198/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/KYMERA-THERAPEUTICS-INC-111169997/news/Kymera-Therapeutics-to-Participate-in-Upcoming-March-Investor-Conferences-43121198/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:02+00:00"
    },
    {
    "author": null,
    "title": "Richter Gedeon Vegyeszeti Gyár Nyilvánosan Muködo Rt : Transactions with Treasury Shares",
    "description": "(marketscreener.com) Extraordinary Announcement Gedeon Richter Plc. hereby announces that on 28 February, 2023 in compliance with the Statutes and Incentive Policy of Richter Gedeon Nyrt. Employee Participation Program Organization it has purchased 223,417 treasury shares on average price of 7,648 HUF/share from the EPP...https://www.marketscreener.com/quote/stock/RICHTER-GEDEON-VEGYESZETI-13611893/news/Richter-Gedeon-Vegyeszeti-Gy-r-Nyilv-nosan-Mukodo-Rt-Transactions-with-Treasury-Shares-43121174/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/RICHTER-GEDEON-VEGYESZETI-13611893/news/Richter-Gedeon-Vegyeszeti-Gy-r-Nyilv-nosan-Mukodo-Rt-Transactions-with-Treasury-Shares-43121174/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:01:21+00:00"
    },
    {
    "author": null,
    "title": "BSE : Additions to the S&P BSE SME IPO Index",
    "description": "(marketscreener.com) PRESS RELEASE Additions to the S&amp;P BSE SME IPO Index MUMBAI, MARCH 01, 2023: With reference to Notice No: 20230228-12 and 20230228-37, Macfos Limited and Sealmatic India Limited respectively, are being listed on the SME Platform of BSE effective Wednesday, March 01, 2023. Effective...https://www.marketscreener.com/quote/stock/BSE-LIMITED-33930062/news/BSE-Additions-to-the-S-P-BSE-SME-IPO-Index-43121172/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/BSE-LIMITED-33930062/news/BSE-Additions-to-the-S-P-BSE-SME-IPO-Index-43121172/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:01:21+00:00"
    },
    {
    "author": null,
    "title": "National Fertilizers : Handling and Transportation Contract ofFertilizers for Warangal Rake Point",
    "description": "(marketscreener.com) &lt;&lt; Back NATIONAL FERTILIZERS LTD NOTICE INVITING TENDER NIT No. ZO/HYD/HT/eTender/2023/078 Dated 01/03/2023 Handling and Transportation Contract ofFertilizers for Warangal Rake Point Click...https://www.marketscreener.com/quote/stock/NATIONAL-FERTILIZERS-LIMI-6498494/news/National-Fertilizers-Handling-and-Transportation-Contract-ofFertilizers-for-Warangal-Rake-Point-43121169/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/NATIONAL-FERTILIZERS-LIMI-6498494/news/National-Fertilizers-Handling-and-Transportation-Contract-ofFertilizers-for-Warangal-Rake-Point-43121169/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:01:20+00:00"
    },
    {
    "author": "ABMN Staff",
    "title": "Clean Energy Fuels Corp. (NASDAQ:CLNE) SVP Barclay Corbus Sells 5,643 Shares of Stock",
    "description": "Clean Energy Fuels Corp. (NASDAQ:CLNE) SVP Barclay Corbus Sells 5,643 Shares of Stock",
    "url": "https://www.americanbankingnews.com/2023/03/01/clean-energy-fuels-corp-nasdaqclne-svp-barclay-corbus-sells-5643-shares-of-stock.html",
    "source": "americanbankingnews",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:04:47+00:00"
    },
    {
    "author": "ABMN Staff",
    "title": "MML Investors Services LLC Purchases 3,823 Shares of Black Knight, Inc. (NYSE:BKI)",
    "description": "MML Investors Services LLC Purchases 3,823 Shares of Black Knight, Inc. (NYSE:BKI)",
    "url": "https://www.americanbankingnews.com/2023/03/01/mml-investors-services-llc-purchases-3823-shares-of-black-knight-inc-nysebki.html",
    "source": "americanbankingnews",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:04:46+00:00"
    },
    {
    "author": "ABMN Staff",
    "title": "MetLife Investment Management LLC Raises Stock Position in Rapid7, Inc. (NASDAQ:RPD)",
    "description": "MetLife Investment Management LLC Raises Stock Position in Rapid7, Inc. (NASDAQ:RPD)",
    "url": "https://www.americanbankingnews.com/2023/03/01/metlife-investment-management-llc-raises-stock-position-in-rapid7-inc-nasdaqrpd.html",
    "source": "americanbankingnews",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:04:46+00:00"
    },
    {
    "author": "ABMN Staff",
    "title": "Bruce R. Berkowitz Sells 1,200 Shares of The St. Joe Company (NYSE:JOE) Stock",
    "description": "Bruce R. Berkowitz Sells 1,200 Shares of The St. Joe Company (NYSE:JOE) Stock",
    "url": "https://www.americanbankingnews.com/2023/03/01/bruce-r-berkowitz-sells-1200-shares-of-the-st-joe-company-nysejoe-stock.html",
    "source": "americanbankingnews",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:48+00:00"
    },
    {
    "author": "Chip Chick",
    "title": "This Dad Paid For His Daughters Wedding, But He is Refusing To Do The Same For His Stepdaughter After She Left Him Off The Guest List",
    "description": "This 56-year-old man got married to his 57-year-old wife, named Lisa, 25 years ago. Together, they have a 24-year-old daughter named April, and Lisa has a 33-year-old daughter named Carly, whom she had with her ex-husband, Doug. Lisa and Doug got divorced when Carly was about 6 because Doug was an addict who wouldn&#8217;t get [&#8230;]",
    "url": "https://www.chipchick.com/2023/03/this-dad-paid-for-his-daughters-wedding-but-hes-refusing-to-do-the-same-for-his-stepdaughter-after-she-left-him-off-the-guest-list.html",
    "source": "chipchick",
    "image": "https://www.chipchick.com/wp-content/uploads/2023/03/AdobeStock_121819479-scaled.jpeg",
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:01:39+00:00"
    },
    {
    "author": "Rahmah Ghazali",
    "title": "British Kebab Awards 2023: Winners for best restaurant and takeaway announced - full list",
    "description": "The winners of British Kebab Awards 2023 have been announced on Tuesday night, celebrating kebab businesses across the UK.",
    "url": "https://www.yorkshireeveningpost.co.uk/read-this/british-kebab-awards-2023-winners-for-best-restaurant-and-takeaway-announced-full-list-4046219",
    "source": "calverleytoday",
    "image": "https://www.yorkshireeveningpost.co.uk/jpim-static/image/2023/03/01/11/GettyImages-1407116766.jpg?width=1200&auto=webp",
    "category": "general",
    "language": "en",
    "country": "uk",
    "published_at": "2023-03-01T12:03:18+00:00"
    },
    {
    "author": "Will Millar",
    "title": "Red Nose Day: BBC reveals list of iconic items viewers can win including Pat Butcher’s earrings - how to enter",
    "description": "BBC is giving viewers the chance to get their hands on some iconic items from television shows this Red Nose Day",
    "url": "https://www.edinburghnews.scotsman.com/read-this/bbc-reveals-list-of-iconic-items-to-win-for-red-nose-day-4046218",
    "source": "edinburghnews",
    "image": "https://www.edinburghnews.scotsman.com/jpim-static/image/2023/03/01/11/Untitled%20design%20%289%29.png?width=1200&auto=webp",
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:41+00:00"
    },
    {
    "author": "AP News",
    "title": "3 Kansas City officers shot while executing search warrant",
    "description": "Authorities say three Kansas City police officers were shot and wounded while executing a search warrant, prompting a standoff at a home",
    "url": "https://www.mymotherlode.com/news/national/2976786/3-kansas-city-officers-shot-while-executing-search-warrant.html",
    "source": "mymotherlode",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:05:29+00:00"
    },
    {
    "author": "AP News",
    "title": "At least 22 people, including children, abducted in Congo",
    "description": "Authorities in Congo say at least 22 people, including children, have been abducted from three villages in the north",
    "url": "https://www.mymotherlode.com/news/africa/2976771/at-least-22-people-including-children-abducted-in-congo.html",
    "source": "mymotherlode",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:05:15+00:00"
    },
    {
    "author": "Will Millar",
    "title": "Red Nose Day: BBC reveals list of iconic items viewers can win including Pat Butchers earrings - how to enter",
    "description": "BBC is giving viewers the chance to get their hands on some iconic items from television shows this Red Nose Day",
    "url": "https://www.wigantoday.net/read-this/bbc-reveals-list-of-iconic-items-to-win-for-red-nose-day-4046218",
    "source": "wigantoday",
    "image": "https://www.wigantoday.net/jpim-static/image/2023/03/01/11/Untitled%20design%20%289%29.png?width=1200&auto=webp",
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:02:41+00:00"
    },
    {
    "author": "Morgan McKenzie",
    "title": "Greeley arson homicide suspects have separate upcoming court hearings",
    "description": "Rodriguez has a hearing set for 1:30 p.m. Friday. Varela will appear for another disposition hearing at 10 a.m. April 11.",
    "url": "https://www.greeleytribune.com/2023/03/01/greeley-arson-homicide-suspects-have-separate-upcoming-court-hearings/",
    "source": "greeleytribune",
    "image": "https://www.greeleytribune.com/wp-content/uploads/2021/11/GRE-L-OctHomicideArrests-02.jpg?w=1400px&strip=all",
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:00:45+00:00"
    },
    {
    "author": "Sekundė",
    "title": "6 profesionalų patarimai, kaip dekoruoti miegamąjį",
    "description": "Jūsų miegamasis &#8211; Jūsų šventovė. Tai vieta, kur galima pailsėti po įtemptos darbo dienos, pabūti su savimi arba prisiglausti prie...The post 6 profesionalų patarimai, kaip dekoruoti miegamąjį appeared first on sekunde.lt.",
    "url": "https://sekunde.lt/leidinys/sekunde/6-profesionalu-patarimai-kaip-dekoruoti-miegamaji/",
    "source": "Sekunde",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "lt",
    "published_at": "2023-03-01T12:05:51+00:00"
    },
    {
    "author": null,
    "title": "Durant'ten Booker'a övgüler:",
    "description": "Phoenix Suns süperstar Kevin Durant, yeni taketbol IQ'suna övgülerde bulundu. Phoenix Suns",
    "url": "https://www.sporx.com/basketbol/nba//durant-ten-booker-a-ovguler-birlikte-oynamayi-dort-gozle-bekliyorum-SXHBQ1008962SXQ?utm_source=icerikPaylas",
    "source": "sporx",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "tr",
    "published_at": "2023-03-01T12:03:00+00:00"
    },
    {
    "author": null,
    "title": "Correction to Royal Bank of Canada Earnings Article",
    "description": "(marketscreener.com) Royal Bank of Canada reported first-quarter earnings Wednesday.  at 6:50 a.m. ET, incorrectly said in the headline that results were for the fourth quarter. https://www.marketscreener.com/quote/stock/ROYAL-BANK-OF-CANADA-1411559/news/Correction-to-Royal-Bank-of-Canada-Earnings-Article-43121331/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/ROYAL-BANK-OF-CANADA-1411559/news/Correction-to-Royal-Bank-of-Canada-Earnings-Article-43121331/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:09:00+00:00"
    },
    {
    "author": null,
    "title": "Telecom operator Veon confirms deal with British satellite firm OneWeb",
    "description": "(marketscreener.com) Telecom operator Veon, which operates Ukraine's largest mobile network, has announced that it is partnering with British satellite firm OneWeb to improve connectivity in rural or disaster-prone areas. https://www.marketscreener.com/quote/stock/VEON-LTD-34473582/news/Telecom-operator-Veon-confirms-deal-with-British-satellite-firm-OneWeb-43121257/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/VEON-LTD-34473582/news/Telecom-operator-Veon-confirms-deal-with-British-satellite-firm-OneWeb-43121257/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:08:34+00:00"
    },
    {
    "author": null,
    "title": "U.S. mortgage interest rates remain at highest level since November - MBA",
    "description": "(marketscreener.com) The average interest rate on the most popular U.S. home loan remained last week at its highest level since November as stronger-than-expected readings on inflation, job gains and consumer spending caused investors to hike their bets that the Federal Reserve will have to keep raising its policy rate through the summer.https://www.marketscreener.com/quote/stock/APPLIED-ENERGETICS-INC-120791498/news/U-S-mortgage-interest-rates-remain-at-highest-level-since-November-MBA-43121226/?utm_medium=RSS&utm_content=20230301",
    "url": "https://www.marketscreener.com/quote/stock/APPLIED-ENERGETICS-INC-120791498/news/U-S-mortgage-interest-rates-remain-at-highest-level-since-November-MBA-43121226/?utm_medium=RSS&utm_content=20230301",
    "source": "4-traders",
    "image": null,
    "category": "general",
    "language": "en",
    "country": "us",
    "published_at": "2023-03-01T12:07:19+00:00"
    }
    ]
    }

exports.response = response;
